### PR TITLE
Add `WinPixEventRuntime` partition

### PR DESCRIPTION
**Pull request by MarijnS95**
Bind the `pix3` header, used to instrument PIX in games. These headers from the `NuGet` package are more up-to-date than the SDK-provided `pix.h`.

https://devblogs.microsoft.com/pix/winpixeventruntime/

#### Overlapping type and member definitions

`pix3.h` contains struct and member definitions in one, with the same name (in a `union`). For example:

```C++
union PIXCaptureParameters
{
    // ...
    struct GpuCaptureParameters
    {
        PCWSTR FileName;
    } GpuCaptureParameters;
    // ...
}
```

It appears C# cannot deal with a nested struct named the same as the field:

```C#
    [StructLayout(LayoutKind.Explicit)]
    public partial struct PIXCaptureParameters
    {
        [FieldOffset(0)]
[NativeTypeName("struct GpuCaptureParameters")]        public GpuCaptureParameters GpuCaptureParameters;

        // ...

        public unsafe partial struct GpuCaptureParameters
        {
[NativeTypeName("PCWSTR"),Const]            public ushort* FileName;
        }

        // ...
    }
```

Resulting in:

```
generation\WinSDK\obj\generated\obj\crossarch\common\WinPixEventRuntime.modified.cs(322,84): error CS0102: The type 'PIXCaptureParameters' already contains a definition for 'GpuCaptureParameters' [generation\WinSDK\Windows.Win32.proj]
generation\WinSDK\obj\generated\obj\crossarch\common\WinPixEventRuntime.modified.cs(325,90): error CS0102: The type 'PIXCaptureParameters' already contains a definition for 'TimingCaptureParameters' [generation\WinSDK\Windows.Win32.proj]
```

Should the nested types simply be renamed, to what, and how?

#### Library

Probably need to add these symbols to `libMappings.rsp` for `WinPixEventRuntime.dll`.

### CODE REVIEW

**Comment by mikebattista** [comment]
These headers are all C++ and inlines which aren't supported in the metadata.

**Comment by MarijnS95** [comment]
@mikebattista that is a little short-sighted to insta-close this PR for.  While it is true that the majority of these headers are inline functions and C++ classes, there are a few magic constants in the header that I'd like to bind in win32metadata rather than copy-pasting by hand.

Is that something win32metadate can accommodate for and reopen the PR, so that I can tune the generator scripts to skip the rest? Thanks in advance.

**Comment by MarijnS95** [comment]
@mikebattista any updates here? Can you reopen this? I'd hate to have to create a separate project hosting just these few constants and structs, and generate Rust code from that.

**Comment by MarijnS95** [comment]
Thanks for reopening this @mikebattista. So far I've managed to get the following constants to generate:

```
Windows.Win32.Graphics.WinPixEventRuntime.Apis.D3D12_EVENT_METADATA added
Windows.Win32.Graphics.WinPixEventRuntime.Apis.PIX_CAPTURE_AUDIO added
Windows.Win32.Graphics.WinPixEventRuntime.Apis.PIX_CAPTURE_CALLGRAPH added
Windows.Win32.Graphics.WinPixEventRuntime.Apis.PIX_CAPTURE_FUNCTION_DETAILS added
Windows.Win32.Graphics.WinPixEventRuntime.Apis.PIX_CAPTURE_FUNCTION_SUMMARY added
Windows.Win32.Graphics.WinPixEventRuntime.Apis.PIX_CAPTURE_GPU added
Windows.Win32.Graphics.WinPixEventRuntime.Apis.PIX_CAPTURE_INSTRUCTION_TRACE added
Windows.Win32.Graphics.WinPixEventRuntime.Apis.PIX_CAPTURE_RESERVED added
Windows.Win32.Graphics.WinPixEventRuntime.Apis.PIX_CAPTURE_SYSTEM_MONITOR_COUNTERS added
Windows.Win32.Graphics.WinPixEventRuntime.Apis.PIX_CAPTURE_TIMING added
Windows.Win32.Graphics.WinPixEventRuntime.Apis.PIX_CAPTURE_VIDEO added
Windows.Win32.Graphics.WinPixEventRuntime.Apis.PIX_ENABLE_BLOCK_ARGUMENT_COPY added
Windows.Win32.Graphics.WinPixEventRuntime.Apis.PIX_ENABLE_BLOCK_ARGUMENT_COPY_SET added
Windows.Win32.Graphics.WinPixEventRuntime.Apis.WINPIX_EVENT_ANSI_VERSION added
Windows.Win32.Graphics.WinPixEventRuntime.Apis.WINPIX_EVENT_PIX3BLOB_VERSION added
Windows.Win32.Graphics.WinPixEventRuntime.Apis.WINPIX_EVENT_UNICODE_VERSION added
Windows.Win32.Graphics.WinPixEventRuntime.PIXCaptureParameters added
Windows.Win32.Graphics.WinPixEventRuntime.PIXHUDOptions added
Windows.Win32.Graphics.WinPixEventRuntime.PIXHUDOptions.PIX_HUD_SHOW_ON_ALL_WINDOWS added
Windows.Win32.Graphics.WinPixEventRuntime.PIXHUDOptions.PIX_HUD_SHOW_ON_NO_WINDOWS added
Windows.Win32.Graphics.WinPixEventRuntime.PIXHUDOptions.PIX_HUD_SHOW_ON_TARGET_WINDOW_ONLY added
```

I'd like to have `PIXEventType` as well, but it's nowhere to be seen. That enum is defined right below `struct PIXEventsThreadInfo`, which strangely was skipped with:

    Info: Visiting win32metadata/generation/WinSDK/RecompiledIdlHeaders/um/pix3_win.h
    Info: Excluded CXXRecord declaration 'PIXEventsThreadInfo' by config option

Is it a feature to stop parsing the header at that point? And can I somehow steer that to get the necessary constants? There are a bunch of shifts and masks directly after that `enum` that are also missing.

---

Note though that this has been generated by manually hacking around the "duplicate" definition in `PIXCaptureParameters`, is there any way I can steer that? The generator also says `Info: Excluded CXXRecord declaration 'PIXCaptureParameters::PIXCaptureParameters' by config option` but `PIXCaptureParameters` is a union that doesn't contain a member nor nested type of the same name.

**Comment by riverar** [comment]
The PIX 3 NuGet package is not compatible with anything in the OS and appears to be completely out of scope for win32metadata. That said, I think it's fair if you open an issue with a specific issue you're having with the _tooling_ to generate your own .winmd.

**Pull request closed without merging**
