### PR TITLE
Add MetadataTasks.dll to Microsoft.Windows.WinmdGenerator package

### LINKED ISSUE #644: winmdgenerator: 0.2.185-preview nuget is broken
MetadataTasks.dll is indeed missing https://nuget.info/packages/Microsoft.Windows.WinmdGenerator/0.2.185-preview

```
Sdk.targets(19,5): error MSB4062: The "MetadataTasks.CompileIdls" task could not be loaded from the assembly
C:\Users\Rafael\.nuget\packages\microsoft.windows.winmdgenerator\0.2.185-preview\tools\net5.0\MetadataTasks.dll.

Could not load file or assembly
'C:\Users\Rafael\.nuget\packages\microsoft.windows.winmdgenerator\0.2.185-preview\tools\net5.0\MetadataTasks.dll'.

The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly
and all its dependencies are available, and that the task contains a public class that implements
Microsoft.Build.Framework.ITask.
```

### PR DESCRIPTION
**Pull request by AArnott**
Fixes #644
This probably regressed in #630

### CODE REVIEW

**Comment by AArnott** [comment]
@riverar thank you for catching this regression. 
Would you be willing to download the package built in this PR and test that it works for you?

**Comment by riverar** [comment]
@AArnott Sure thing, happy to help. Standby.

**Comment by riverar** [comment]
@AArnott I don't have access to the build artifacts.

**Comment by AArnott** [comment]
Shoot. I see that now. I may revise these pipelines to work on a public server sometime.
In the meantime, here they are:
[NuGetPackages.zip](https://github.com/microsoft/win32metadata/files/7141074/NuGetPackages.zip)

**Comment by riverar** [comment]
```
C:\Users\Rafael\.nuget\packages\microsoft.windows.winmdgenerator\0.2.192-preview-g2bb59a68b1\Sdk\Sdk.targets(19,5):
error MSB4044: The "CompileIdls" task was not given a value for the required parameter "SdkBinDir"
```

**Comment by AArnott** [comment]
It looks like that task parameter is supplied by the `WindowsSDKVersionedBinRoot` msbuild property, but I can't find anywhere in this repo where that property has ever been set.

https://github.com/microsoft/win32metadata/blob/931fa65996fef1d6139bd2fe7e4ddc59a8fb7e02/sources/msbuild/sdk/sdk.targets#L25

This task was added in 8ac2e153551e, and this shipped for the first time in the most recent release. @sotteson1 can you please take a look and push a fix to this PR and complete when ready?

**Comment by sotteson1** [comment]
> It looks like that task parameter is supplied by the `WindowsSDKVersionedBinRoot` msbuild property, but I can't find anywhere in this repo where that property has ever been set.

It gets set by the Microsoft.Windows.SDK.cpp package. I'll take a look at the PR and make sure this gets fixed.

**Comment by AArnott** [comment]
Closed because my changes were squashed in #649.

**Pull request closed without merging**
