### PR TITLE
Add additional AlternateSuccessCodes

### PR DESCRIPTION
**Pull request by dqtsth**
Hi i make search on google for "IEnum next site:https://docs.microsoft.com/en-us/windows/win32/" and found more methods with other return codes. Some return S_FALSE also IDirectorySearch and IADsPropertyList I find return other S_ codes like here https://docs.microsoft.com/en-us/windows/win32/adsi/generic-adsi-error-codes

### CODE REVIEW

**Comment by mikebattista** [comment]
Thanks for providing the list.

Per https://github.com/microsoft/win32metadata/issues/559#issuecomment-908509892 we will be replacing the AlternateSuccessCodes attribute with just DllImport.PreserveSig. Once we do that, we'll update the design here to include the list.

**Comment by kennykerr** [comment]
This is blocking customers: https://github.com/microsoft/windows-rs/issues/1371#issuecomment-988682189

> Per #559 (comment) we will be replacing the AlternateSuccessCodes attribute with just DllImport.PreserveSig. Once we do that, we'll update the design here to include the list.

Can we take this PR in the short term or are we planning on completing the replacement some time soon?

**Comment by mikebattista** [comment]
I'll merge this in the short term.

**Comment by mikebattista** [comment]
Merged. @sotteson1 will push a new metadata package to NuGet once the CI build finishes.

**Pull request merged**
