### PR TITLE
Sign the Microsoft.Windows.Sdk.Win32Docs.dll assembly

### PR DESCRIPTION
**Pull request by AArnott**
We need to build it, sign it, then pack it.

### CODE REVIEW

**Comment by AArnott** [comment]
I've verified that the dll is now signed, and that the docs package gets a new version so that it will actually push.

**Review by mikebattista — APPROVED** [review]

**Comment by riverar** [comment]
What's the new assembly for?

**Comment by AArnott** [comment]
What new assembly? This change doesn't introduce a new assembly. It just signs an existing one.
If you're wondering what Microsoft.Windows.Sdk.Win32docs.dll is for, it just defines the schema for the apidocs.msgpack file.

**Comment by riverar** [comment]
Ah neat, thanks. Wasn't familiar with this assembly.

**Comment by timsneath** [comment]
@AArnott is it documented somewhere by any chance?

**Comment by timsneath** [comment]
Is it used by another projection like C#? If there's some existing code that could act as a breadcrumb trail for me to follow, I'd appreciate anything you can offer!

**Comment by AArnott** [comment]
@timsneath, breadcrumb follows:
1. note [the nuget dependency from my projection to the docs package](https://www.nuget.org/packages/microsoft.windows.cswin32#dependencies-body-tab). See also [source](https://github.com/microsoft/CsWin32/blob/78b48564d09b671eb707862c416e990609c5ff74/src/Microsoft.Windows.CsWin32/Microsoft.Windows.CsWin32.nuspec#L20). This package contains both the assembly that defines the schema and the msgpack docs content itself.
2. [How I deserialize the docs file](https://github.com/microsoft/CsWin32/blob/main/src/Microsoft.Windows.CsWin32/Docs.cs). IIRC `ApiDetails` is the type defined within the Microsoft.Windows.Sdk.Win32Docs.dll assembly. I *find* the file to deserialize [via an msbuild property](https://github.com/microsoft/CsWin32/blob/78b48564d09b671eb707862c416e990609c5ff74/src/Microsoft.Windows.CsWin32/SourceGenerator.cs#L378-L404) that [is set here](https://github.com/microsoft/CsWin32/blob/78b48564d09b671eb707862c416e990609c5ff74/src/Microsoft.Windows.CsWin32/build/Microsoft.Windows.CsWin32.props#L21) based on [an msbuild item that is defined by the docs package itself](https://github.com/microsoft/win32metadata/blob/d3ecea2d1d6ee3ca757569d6bfa2fb955b87fb6b/apidocs/Microsoft.Windows.SDK.Win32Docs/buildTransitive/Microsoft.Windows.SDK.Win32Docs.props#L3).
3. [How I actually produce the source doc comments in the emitted code](https://github.com/microsoft/CsWin32/blob/main/src/Microsoft.Windows.CsWin32/Generator.ApiDocs.cs).

**Comment by timsneath** [comment]
Thanks Andrew! I'll take a look.

**Pull request merged**
