### PR TITLE
Add new Retained attribute to OVERLAPPED parameters

### PR DESCRIPTION
**Pull request by riverar**
Fixes: #1726

Add a new `Retained` attribute to indicate when pointers to structures must remain allocated throughout the lifetime of an [asynchronous operation](https://learn.microsoft.com/windows/win32/fileio/synchronous-and-asynchronous-i-o).

### CODE REVIEW

**Review by AArnott — DISMISSED** [review]
This looks good. But what about [`DeviceIoControl`](https://learn.microsoft.com/en-us/windows/win32/api/ioapiset/nf-ioapiset-deviceiocontrol)? Are there other APIs that use `OVERLAPPED` pointers that we should include in this?

**Comment by mikebattista** [comment]
@riverar can you respond to @aarnott's questions?

**Comment by riverar** [comment]
Thanks for the ping. I can add those to this PR too. Standby.

**Comment by AArnott** [comment]
@riverar any update?

**Comment by riverar** [comment]
Catching up on PRs now, good timing. Adding now.

**Comment by riverar** [comment]
Updated. If I missed any APIs, happy to add them.

**Review by AArnott — DISMISSED** [review]

**Review by mikebattista — APPROVED** [review]

**Pull request merged**
