### PR TITLE
Add .dll suffix to remaining library mappings

### PR DESCRIPTION
**Pull request by riverar**
Removes remaining library name ambiguity in metadata. This makes it easier, for example, for downstream projections to create import libraries. (Libraries that had non-`.dll` suffixes, such as `.ax` and `.drv`, were already fully qualified in earlier commits.)

Fixes: #1021

### CODE REVIEW

**Comment by riverar** [comment]
@AArnott This won't mess anything up on your end right? Just double-checking.

**Comment by mikebattista** [comment]
> @AArnott This won't mess anything up on your end right? Just double-checking.

@AArnott could you please review?

**Review by mikebattista — CHANGES_REQUESTED** [review]
Pending approval from @AArnott.

**Review by AArnott — APPROVED** [review]
Thanks for checking. I don't anticipate any problems. And if there are, I'm confident CsWin32 can be changed to accommodate them.

**Review by mikebattista — APPROVED** [review]

**Comment by mikebattista** [comment]
The baseline winmd from this was getting flagged by Windows Defender with a Trojan, so I reverted main.

image

You should take a look at what's going on. You'll need to rebuild and resubmit this change.

**Pull request merged**
