### PR TITLE
Add COLORREF

### LINKED ISSUE #1035: Add COLORREF to CsWin32
**Is your feature request related to a problem? Please describe.**
We refer to `COLORREF` many times inside our code therefore it would be very useful if it was defined in CsWin32.

**Describe the solution you'd like**
Add `COLORREF` to CsWin32
- [Link to COLORREF documentation](https://docs.microsoft.com/en-us/windows/win32/gdi/colorref)

**Describe alternatives you've considered**
We've been using our [own COLORREF struct](https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms.Primitives/src/Interop/Interop.COLORREF.cs)

### PR DESCRIPTION
**Pull request by elachlan**
Fixes #1035
Related: https://github.com/dotnet/winforms/issues/7468

**API Changes**
```
Windows.Win32.System.Console.CONSOLE_SCREEN_BUFFER_INFOEX.ColorTable...System.UInt32[] => Windows.Win32.Foundation.COLORREF[]
Windows.Win32.UI.Controls.RichEdit.TABLECELLPARMS.crBrdrLeft...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.Controls.RichEdit.TABLECELLPARMS.crBrdrTop...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.Controls.RichEdit.TABLECELLPARMS.crBrdrRight...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.Controls.RichEdit.TABLECELLPARMS.crBrdrBottom...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.Controls.RichEdit.TABLECELLPARMS.crBackPat...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.Controls.RichEdit.TABLECELLPARMS.crForePat...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.Controls.RichEdit.CHARFORMATA.crTextColor...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.Controls.RichEdit.CHARFORMATW.crTextColor...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.Controls.RichEdit.CHARFORMAT2W.crBackColor...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.Controls.RichEdit.CHARFORMAT2A.crBackColor...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.Controls.RichEdit.COMPCOLOR.crText...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.Controls.RichEdit.COMPCOLOR.crBackground...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.Controls.RichEdit.ITextHost.TxGetSysColor : return...UInt32 => COLORREF
Windows.Win32.UI.Controls.RichEdit.ITextDocument2Old.SetEffectColor : cr...UInt32 => COLORREF
Windows.Win32.UI.Controls.RichEdit.ITextDocument2Old.GetEffectColor : pcr...UInt32* => COLORREF*
Windows.Win32.Graphics.DirectWrite.IDWriteBitmapRenderTarget.DrawGlyphRun : textColor...UInt32 => COLORREF
Windows.Win32.Graphics.Gdi.LOGBRUSH.lbColor...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.Graphics.Gdi.LOGBRUSH32.lbColor...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.Graphics.Gdi.LOGPEN.lopnColor...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.Graphics.Gdi.EXTLOGPEN.elpColor...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.Graphics.Gdi.EXTLOGPEN32.elpColor...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.Graphics.Gdi.EMRSETTEXTCOLOR.crColor...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.Graphics.Gdi.EMRSETPIXELV.crColor...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.Graphics.Gdi.EMREXTFLOODFILL.crColor...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.Graphics.Gdi.EMRBITBLT.crBkColorSrc...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.Graphics.Gdi.EMRSTRETCHBLT.crBkColorSrc...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.Graphics.Gdi.EMRMASKBLT.crBkColorSrc...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.Graphics.Gdi.EMRPLGBLT.crBkColorSrc...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.Graphics.Gdi.EMRALPHABLEND.crBkColorSrc...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.Graphics.Gdi.EMRTRANSPARENTBLT.crBkColorSrc...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.Graphics.OpenGL.LAYERPLANEDESCRIPTOR.crTransparent...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.Data.HtmlHelp.HH_POPUP.clrForeground...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.Data.HtmlHelp.HH_POPUP.clrBackground...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.Media.DirectShow.COLORKEY.LowColorValue...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.Media.DirectShow.COLORKEY.HighColorValue...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.Media.DirectShow.IVMRSurfaceAllocatorNotify.SetBorderColor : clrBorder...UInt32 => COLORREF
Windows.Win32.Media.DirectShow.IVMRWindowlessControl.SetBorderColor : Clr...UInt32 => COLORREF
Windows.Win32.Media.DirectShow.IVMRWindowlessControl.GetBorderColor : lpClr...UInt32* => COLORREF*
Windows.Win32.Media.DirectShow.IVMRWindowlessControl.SetColorKey : Clr...UInt32 => COLORREF
Windows.Win32.Media.DirectShow.IVMRWindowlessControl.GetColorKey : lpClr...UInt32* => COLORREF*
Windows.Win32.Media.DirectShow.IVMRMixerControl.SetBackgroundClr : ClrBkg...UInt32 => COLORREF
Windows.Win32.Media.DirectShow.IVMRMixerControl.GetBackgroundClr : lpClrBkg...UInt32* => COLORREF*
Windows.Win32.Media.DirectShow.VMRALPHABITMAP.clrSrcKey...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.Media.DirectShow.IVMRWindowlessControl9.SetBorderColor : Clr...UInt32 => COLORREF
Windows.Win32.Media.DirectShow.IVMRWindowlessControl9.GetBorderColor : lpClr...UInt32* => COLORREF*
Windows.Win32.Media.DirectShow.IVMRMixerControl9.SetBackgroundClr : ClrBkg...UInt32 => COLORREF
Windows.Win32.Media.DirectShow.IVMRMixerControl9.GetBackgroundClr : lpClrBkg...UInt32* => COLORREF*
Windows.Win32.Media.DirectShow.VMR9AlphaBitmap.clrSrcKey...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.System.Mmc.IImageList.ImageListSetStrip : cMask...UInt32 => COLORREF
Windows.Win32.System.Mmc.IToolbar.AddBitmap : crMask...UInt32 => COLORREF
Windows.Win32.System.Mmc.ISnapinAbout.GetStaticFolderImage : cMask...UInt32* => COLORREF*
Windows.Win32.UI.TabletPC.INKMETRIC.color...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.TextServices.TF_DA_COLOR._Anonymous_e__Union.cr...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.Controls.COLORSCHEME.clrBtnHighlight...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.Controls.COLORSCHEME.clrBtnShadow...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.Controls.IMAGELISTDRAWPARAMS.rgbBk...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.Controls.IMAGELISTDRAWPARAMS.rgbFg...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.Controls.IMAGELISTDRAWPARAMS.crEffect...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.Controls.COLORMAP.from...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.Controls.COLORMAP.to...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.Controls.NMTBCUSTOMDRAW.clrText...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.Controls.NMTBCUSTOMDRAW.clrMark...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.Controls.NMTBCUSTOMDRAW.clrTextHighlight...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.Controls.NMTBCUSTOMDRAW.clrBtnFace...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.Controls.NMTBCUSTOMDRAW.clrBtnHighlight...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.Controls.NMTBCUSTOMDRAW.clrHighlightHotTrack...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.Controls.REBARBANDINFOA.clrFore...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.Controls.REBARBANDINFOA.clrBack...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.Controls.REBARBANDINFOW.clrFore...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.Controls.REBARBANDINFOW.clrBack...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.Controls.LVGROUPMETRICS.crLeft...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.Controls.LVGROUPMETRICS.crTop...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.Controls.LVGROUPMETRICS.crRight...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.Controls.LVGROUPMETRICS.crBottom...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.Controls.LVGROUPMETRICS.crHeader...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.Controls.LVGROUPMETRICS.crFooter...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.Controls.NMLVCUSTOMDRAW.clrText...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.Controls.NMLVCUSTOMDRAW.clrTextBk...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.Controls.NMLVCUSTOMDRAW.clrFace...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.Controls.NMTVCUSTOMDRAW.clrText...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.Controls.NMTVCUSTOMDRAW.clrTextBk...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.Controls.IImageList.AddMasked : crMask...UInt32 => COLORREF
Windows.Win32.UI.Controls.IImageList.SetBkColor : clrBk...UInt32 => COLORREF
Windows.Win32.UI.Controls.IImageList.SetBkColor : pclr...UInt32* => COLORREF*
Windows.Win32.UI.Controls.IImageList.GetBkColor : pclr...UInt32* => COLORREF*
Windows.Win32.UI.Controls.DTTOPTS.crText...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.Controls.DTTOPTS.crBorder...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.Controls.DTTOPTS.crShadow...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.Controls.Dialogs.CHOOSECOLORA.rgbResult...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.Controls.Dialogs.CHOOSECOLORA.lpCustColors...System.UInt32* => Windows.Win32.Foundation.COLORREF*
Windows.Win32.UI.Controls.Dialogs.CHOOSECOLORW.rgbResult...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.Controls.Dialogs.CHOOSECOLORW.lpCustColors...System.UInt32* => Windows.Win32.Foundation.COLORREF*
Windows.Win32.UI.Controls.Dialogs.CHOOSEFONTA.rgbColors...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.Controls.Dialogs.CHOOSEFONTW.rgbColors...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.WindowsAndMessaging.UPDATELAYEREDWINDOWINFO.crKey...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.Media.MediaFoundation.IMFCapturePreviewSink.UpdateVideo : pBorderClr...UInt32* => COLORREF*
Windows.Win32.Media.MediaFoundation.IMFVideoDisplayControl.SetBorderColor : Clr...UInt32 => COLORREF
Windows.Win32.Media.MediaFoundation.IMFVideoDisplayControl.GetBorderColor : pClr...UInt32* => COLORREF*
Windows.Win32.Media.MediaFoundation.IMFPMediaPlayer.SetBorderColor : Clr...UInt32 => COLORREF
Windows.Win32.Media.MediaFoundation.IMFPMediaPlayer.GetBorderColor : pClr...UInt32* => COLORREF*
Windows.Win32.Media.MediaFoundation.IMFVideoProcessor.GetBackgroundColor : lpClrBkg...UInt32* => COLORREF*
Windows.Win32.Media.MediaFoundation.IMFVideoProcessor.SetBackgroundColor : ClrBkg...UInt32 => COLORREF
Windows.Win32.Media.MediaFoundation.MFVideoAlphaBitmapParams.clrSrcKey...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.Shell.IPreviewHandlerVisuals.SetBackgroundColor : color...UInt32 => COLORREF
Windows.Win32.UI.Shell.IPreviewHandlerVisuals.SetTextColor : color...UInt32 => COLORREF
Windows.Win32.UI.Shell.SHDRAGIMAGE.crColorKey...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.Shell.DESKBANDINFO.crBkgnd...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.Shell.IDesktopWallpaper.SetBackgroundColor : color...UInt32 => COLORREF
Windows.Win32.UI.Shell.IDesktopWallpaper.GetBackgroundColor : color...UInt32* => COLORREF*
Windows.Win32.UI.Shell.IVisualProperties.SetColor : cr...UInt32 => COLORREF
Windows.Win32.UI.Shell.IVisualProperties.GetColor : pcr...UInt32* => COLORREF*
Windows.Win32.UI.Shell.INameSpaceTreeControlCustomDraw.ItemPrePaint : pclrText...UInt32* => COLORREF*
Windows.Win32.UI.Shell.INameSpaceTreeControlCustomDraw.ItemPrePaint : pclrTextBk...UInt32* => COLORREF*
Windows.Win32.UI.Shell.NT_CONSOLE_PROPS.ColorTable...System.UInt32[] => Windows.Win32.Foundation.COLORREF[]
Windows.Win32.UI.Shell.BANDINFOSFB.crBkgnd...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.Shell.BANDINFOSFB.crBtnLt...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.Shell.BANDINFOSFB.crBtnDk...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.Controls.Dialogs.CHOOSECOLORA.rgbResult...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.Controls.Dialogs.CHOOSECOLORA.lpCustColors...System.UInt32* => Windows.Win32.Foundation.COLORREF*
Windows.Win32.UI.Controls.Dialogs.CHOOSECOLORW.rgbResult...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.Controls.Dialogs.CHOOSECOLORW.lpCustColors...System.UInt32* => Windows.Win32.Foundation.COLORREF*
Windows.Win32.UI.Controls.Dialogs.CHOOSEFONTA.rgbColors...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.UI.Controls.Dialogs.CHOOSEFONTW.rgbColors...System.UInt32 => Windows.Win32.Foundation.COLORREF
Windows.Win32.Foundation.COLORREF not found in 1st winmd
Windows.Win32.UI.Controls.Apis.ImageList_SetBkColor : return...UInt32 => COLORREF
Windows.Win32.UI.Controls.Apis.ImageList_SetBkColor : clrBk...UInt32 => COLORREF
Windows.Win32.UI.Controls.Apis.ImageList_GetBkColor : return...UInt32 => COLORREF
Windows.Win32.UI.Controls.Apis.ImageList_AddMasked : crMask...UInt32 => COLORREF
Windows.Win32.UI.Controls.Apis.ImageList_DrawEx : rgbBk...UInt32 => COLORREF
Windows.Win32.UI.Controls.Apis.ImageList_DrawEx : rgbFg...UInt32 => COLORREF
Windows.Win32.UI.Controls.Apis.ImageList_LoadImageA : crMask...UInt32 => COLORREF
Windows.Win32.UI.Controls.Apis.ImageList_LoadImageW : crMask...UInt32 => COLORREF
Windows.Win32.UI.Controls.Apis.DrawShadowText : crText...UInt32 => COLORREF
Windows.Win32.UI.Controls.Apis.DrawShadowText : crShadow...UInt32 => COLORREF
Windows.Win32.UI.Controls.Apis.GetThemeColor : pColor...UInt32* => COLORREF*
Windows.Win32.UI.Controls.Apis.GetThemeSysColor : return...UInt32 => COLORREF
Windows.Win32.Graphics.Gdi.Apis.CreateHatchBrush : color...UInt32 => COLORREF
Windows.Win32.Graphics.Gdi.Apis.CreatePen : color...UInt32 => COLORREF
Windows.Win32.Graphics.Gdi.Apis.CreateSolidBrush : color...UInt32 => COLORREF
Windows.Win32.Graphics.Gdi.Apis.ExtFloodFill : color...UInt32 => COLORREF
Windows.Win32.Graphics.Gdi.Apis.FloodFill : color...UInt32 => COLORREF
Windows.Win32.Graphics.Gdi.Apis.GetBkColor : return...UInt32 => COLORREF
Windows.Win32.Graphics.Gdi.Apis.GetDCBrushColor : return...UInt32 => COLORREF
Windows.Win32.Graphics.Gdi.Apis.GetDCPenColor : return...UInt32 => COLORREF
Windows.Win32.Graphics.Gdi.Apis.GetNearestColor : return...UInt32 => COLORREF
Windows.Win32.Graphics.Gdi.Apis.GetNearestColor : color...UInt32 => COLORREF
Windows.Win32.Graphics.Gdi.Apis.GetNearestPaletteIndex : color...UInt32 => COLORREF
Windows.Win32.Graphics.Gdi.Apis.GetPixel : return...UInt32 => COLORREF
Windows.Win32.Graphics.Gdi.Apis.GetTextColor : return...UInt32 => COLORREF
Windows.Win32.Graphics.Gdi.Apis.SetBkColor : return...UInt32 => COLORREF
Windows.Win32.Graphics.Gdi.Apis.SetBkColor : color...UInt32 => COLORREF
Windows.Win32.Graphics.Gdi.Apis.SetDCBrushColor : return...UInt32 => COLORREF
Windows.Win32.Graphics.Gdi.Apis.SetDCBrushColor : color...UInt32 => COLORREF
Windows.Win32.Graphics.Gdi.Apis.SetDCPenColor : return...UInt32 => COLORREF
Windows.Win32.Graphics.Gdi.Apis.SetDCPenColor : color...UInt32 => COLORREF
Windows.Win32.Graphics.Gdi.Apis.SetPixel : return...UInt32 => COLORREF
Windows.Win32.Graphics.Gdi.Apis.SetPixel : color...UInt32 => COLORREF
Windows.Win32.Graphics.Gdi.Apis.SetPixelV : color...UInt32 => COLORREF
Windows.Win32.Graphics.Gdi.Apis.SetTextColor : return...UInt32 => COLORREF
Windows.Win32.Graphics.Gdi.Apis.SetTextColor : color...UInt32 => COLORREF
Windows.Win32.System.Ole.Apis.OleTranslateColor : lpcolorref...UInt32* => COLORREF*
Windows.Win32.UI.Shell.Apis.ColorRGBToHLS : clrRGB...UInt32 => COLORREF
Windows.Win32.UI.Shell.Apis.ColorHLSToRGB : return...UInt32 => COLORREF
Windows.Win32.UI.Shell.Apis.ColorAdjustLuma : return...UInt32 => COLORREF
Windows.Win32.UI.Shell.Apis.ColorAdjustLuma : clrRGB...UInt32 => COLORREF
Windows.Win32.Graphics.OpenGL.Apis.wglSetLayerPaletteEntries : param4...UInt32* => COLORREF*
Windows.Win32.Graphics.OpenGL.Apis.wglGetLayerPaletteEntries : param4...UInt32* => COLORREF*
Windows.Win32.UI.ColorSystem.Apis.CMTranslateRGB : ColorRef...UInt32 => COLORREF
Windows.Win32.UI.WindowsAndMessaging.Apis.UpdateLayeredWindow : crKey...UInt32 => COLORREF
Windows.Win32.UI.WindowsAndMessaging.Apis.GetLayeredWindowAttributes : pcrKey...UInt32* => COLORREF*
Windows.Win32.UI.WindowsAndMessaging.Apis.SetLayeredWindowAttributes : crKey...UInt32 => COLORREF
Windows.Win32.UI.WindowsAndMessaging.Apis.SetSysColors : lpaRgbValues...UInt32* => COLORREF*
```

### CODE REVIEW

**Comment by elachlan** [comment]
CC: @JeremyKuhne

**Review by AArnott — APPROVED** [review]

**Review by sotteson1 — COMMENTED** [review]
The new system gets rid of the baseline .winmd, and instead updates a text file that will include the diff of your changes. (The output of the build is meant to help you automate your additions to this file.) Sorry to randomize your PR but I think this system will be a lot nicer for merges in the future.

**Comment by elachlan** [comment]
@sotteson1 I tried to make the change but I recieve this error at the end of the build:
```
Write-Error: D:\Development\win32metadata\scripts\TestWinmdBinary.ps1:24
Line |
  24 |  & "$PSScriptRoot\CompareBinToLastRelease.ps1" -SkipInstallTools
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | If all the differences are expected, please update the expected differences list:
     | .\scripts\UpdateChangesSinceLastRelease.ps1 '<add a reason here>'
```

**Comment by sotteson1** [comment]
> @sotteson1 I tried to make the change but I recieve this error at the end of the build:
> 
> ```
> Write-Error: D:\Development\win32metadata\scripts\TestWinmdBinary.ps1:24
> Line |
>   24 |  & "$PSScriptRoot\CompareBinToLastRelease.ps1" -SkipInstallTools
>      |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>      | If all the differences are expected, please update the expected differences list:
>      | .\scripts\UpdateChangesSinceLastRelease.ps1 '<add a reason here>'
> ```

Yes, by design. This allows us to no longer have the baseline .winmd, which is impossible to merge. Once you run the script, you can run the test again to make sure things are in a good state.

**Review by sotteson1 — APPROVED** [review]
Thanks for the fix!

**Pull request merged**
