### PR TITLE
Remove empty value type `IStiDeviceW` in favor of `IStiDevice`

### LINKED ISSUE #955: `Windows.Win32.Devices.Fax.IStiDeviceW` is an empty type
I think this should be excluded from generation. 

The MSIL shows:
```msil
.class /* 02002632 */ public sequential ansi sealed beforefieldinit Windows.Win32.Devices.Fax.IStiDeviceW
	extends [netstandard]System.ValueType
{
} // end of class Windows.Win32.Devices.Fax.IStiDeviceW
```

There's a separate type, Windows.Win32.Devices.Fax.IStiDevice, which is fully populated and is I think the only necessary interface.

### PR DESCRIPTION
**Pull request by timsneath**
Fixes #955

### CODE REVIEW

**Comment by kennykerr** [comment]
@mikebattista / @sotteson1 seems like a simple enough PR - got a moment for a review?

**Review by mikebattista — APPROVED** [review]

**Comment by mikebattista** [comment]
Merged. I trust that you checked the diff and saw the expected changes in the results.

**Comment by timsneath** [comment]
Yup - my first time doing this: picked something super small that was a source of irritation :) But I checked the diff and the change is contained to this one valuetype. Thanks!

**Comment by mikebattista** [comment]
Thanks for the contribution!

**Pull request merged**
