### PR TITLE
Initial support for GDI+

### LINKED ISSUE #1287: `Gdiplus` missing some functions/enums `GdipCreateSolidFill`, `GdipCloneBrush`, `GpStatus`
https://learn.microsoft.com/en-au/windows/win32/api/gdiplustypes/ne-gdiplustypes-status

GdipCreateSolidFill
https://learn.microsoft.com/en-us/windows/win32/gdiplus/-gdiplus-solidbrush-flat

GdipCloneBrush
https://learn.microsoft.com/en-us/windows/win32/gdiplus/-gdiplus-brush-flat

I can't find the direct documentation on it.

Winforms tracking: https://github.com/dotnet/winforms/issues/7468

### PR DESCRIPTION
**Pull request by riverar**
Fixes #1287

### CODE REVIEW

**Comment by riverar** [comment]
Quick Rust sample

```rust
use windows::{
    core::w,
    Win32::Graphics::GdiPlus::{
        self, GdipCreateFontFamilyFromName, GdipNewInstalledFontCollection, GdiplusShutdown,
        GdiplusStartup, GdiplusStartupInput, GpFontCollection, GpFontFamily,
    },
};

fn main() -> windows::core::Result<()> {
    unsafe {
        let mut token = usize::default();
        let input = GdiplusStartupInput {
            GdiplusVersion: 1,
            ..Default::default()
        };

        assert_eq!(
            GdiplusStartup(&mut token, &input, std::ptr::null_mut()),
            GdiPlus::Ok
        );

        let mut collection: *mut GpFontCollection = std::ptr::null_mut();
        assert_eq!(
            GdipNewInstalledFontCollection(&mut collection as *mut *mut _),
            GdiPlus::Ok
        );

        let mut family: *mut GpFontFamily = std::ptr::null_mut();
        assert_eq!(
            GdipCreateFontFamilyFromName(w!("Segoe UI"), collection, &mut family as *mut *mut _),
            GdiPlus::Ok
        );
        assert_eq!(
            GdipCreateFontFamilyFromName(
                w!("Invalid Font Family"),
                collection,
                &mut family as *mut *mut _
            ),
            GdiPlus::FontFamilyNotFound
        );

        GdiplusShutdown(token);
    }

    Ok(())
}

```

**Comment by riverar** [comment]
@elachlan Which Gdi+ APIs are you using? I'd like to make sure we have coverage here.

**Review by mikebattista — APPROVED** [review]

**Comment by mikebattista** [comment]
Awesome. Thanks!

**Comment by riverar** [comment]
@mikebattista You okay with the separate `Windows.Win32.Graphics.GdiPlus` namespace? I figured folks that want to use a few standard GDI APIs didn't want to shoulder the burden of all the GDI+ goop.

**Comment by mikebattista** [comment]
Yes that seemed reasonable.

**Comment by JeremyKuhne** [comment]
> Which Gdi+ APIs are you using? I'd like to make sure we have coverage here.

@riverar Most of them. WinForms owns System.Drawing which is mostly a wrap of GDI+.  You can see some of them here:

https://github.com/dotnet/winforms/blob/main/src/System.Drawing.Common/src/System/Drawing/GdiplusNative.DllImport.cs

**Comment by riverar** [comment]
Thanks @JeremyKuhne @elachlan will take a look. Think we got them all covered.

@mikebattista Looks like build validation didn't run in this PR and some tests failed that need fixes. Will clean that up today and submit another PR.

**Comment by riverar** [comment]
@mikebattista Can do!

**Comment by riverar** [comment]
@mikebattista Given the following:

```
Duplicate types detected:
 POINTF(X,Y)
   Windows.Win32.Graphics.GdiPlus
   Windows.Win32.System.Ole
 POINT(X,Y)
   Windows.Win32.Foundation
   Windows.Win32.Graphics.GdiPlus
 DEBUGEVENTPROC(INVOKE)
   Windows.Win32.Graphics.GdiPlus
   Windows.Win32.System.VirtualDosMachines
```

I can move them to common areas but how do you then map to them via each partition? Or do we exclude them from both?

**Comment by mikebattista** [comment]
What do you mean by map to them via each partition?

**Comment by riverar** [comment]
Ole and Gdiplus both need a PointF. Is the workflow: Create a common PointF, exclude PointF from each partition?

**Comment by mikebattista** [comment]
Is just remapping in requiredNamespacesForNames not enough?

**Pull request merged**
