### PR TITLE
Added MidlSwitches for #1428.

### PR DESCRIPTION
**Pull request by mikebattista**
I followed the existing pattern for AdditionalIncludes to add MidlSwitches for #1428.

### CODE REVIEW

**Comment by mikebattista** [comment]
@benkuhn if we wanted to set /notlb as the default, I believe we would make that change in `commonMidlArgs`.

**Review by BenJKuhn — APPROVED** [review]

**Review by abolade — APPROVED** [review]
This looks fine for simply appending switches to the midl.exe command line.

If the command line needs to be replaced, a different approach might be needed: check if MidlSwitches is null or empty and, if so, use the defaults currently set in commonMidlArgs; otherwise, use the contents of MidlSwitches *instead of* the defaults currently set in commonMidlArgs.

**Comment by mikebattista** [comment]
Thanks. For now, I'd like to start with being able to append flags that are missing.

Unless we want to make a change to set /notld by default per @benkuhn's comments, then we can set that switch in the default arguments.

Are there other MIDL parameters that would need to be appended in this way besides /notld? If we made /notld the default, would we still want to have this ability to append additional arguments?

**Review by chenss3 — APPROVED** [review]

**Comment by mikebattista** [comment]
If we want to keep this, I believe the below would also need to be updated to pass through the user-defined switches to the CompileIdls Task.

https://github.com/microsoft/win32metadata/blob/e6e1456e6ca0251d6d23134b80b242280bb841be/sources/GeneratorSdk/sdk/sdk.targets#L124-L133

**Review by BenJKuhn — DISMISSED** [review]

**Comment by mikebattista** [comment]
What are the implications of setting /notld by default? Is that expected to work in all scenarios?

**Comment by kennykerr** [comment]
That should be safe. Since you aren't consuming tlb files, you can safely avoid generating them.

**Comment by mikebattista** [comment]
Ok. I will set it by default and leave the custom additional flags support in. It's optional so there's no harm in leaving it there as an experiment.

**Pull request merged**
