### PR TITLE
Adjust PreserveSig emission

### LINKED ISSUE #559: Add an attribute for identifying methods and functions that return alternative success codes
For example `DoDragDrop` returns `DRAGDROP_S_DROP` on successful drop. However there doesn't seem to be any way to retrieve this value, since windows-rs immediately calls `ok()` on the `HRESULT`. And given that `DRAGDROP_S_DROP` doesn't have the error bit set it is not passed as error in the `Result`.

Is this an oversight?

### PR DESCRIPTION
**Pull request by riverar**
Fixes #559

Removes PreserveSig emission for all APIs by default. Adds PreserveSig emission for class methods explicitly marked with `[PreserveSig]` in `emitter.settings.rsp`. (Interface methods were already covered previously.)

Metadata diff is too large to be useful, as you can imagine.

### CODE REVIEW

**Review by sotteson1 — APPROVED** [review]

**Comment by AArnott** [comment]
FWIW I feel PreserveSig should remain on standard C methods. Only the COM interface methods should lack preservesig because those are the ones we expect to be projected with a different signature.

**Comment by kennykerr** [comment]
Hate to disagree but I've been applying transformations on methods and free functions alike and it would be a major step back not to. Developers love it.

**Comment by AArnott** [comment]
@kennykerr I'm very curious now. Are you saying that win32 methods like CreateFile don't return values anymore? Methods that return hresult, win32 error codes, lstatus, etc... will throw instead of return error codes?

**Comment by AArnott** [comment]
That makes sense. In CsWin32 we can deal with it either way, so if it's useful to you as-is, that's fine by me.

**Pull request merged**
