### PR TITLE
cleanup the `enums.json` to make sure it validates

### PR DESCRIPTION
**Pull request by elachlan**
cleaning up mistakes in the enums.json

```
Unknown differences found:
Windows.Win32.System.Com.ITypeInfo.GetImplTypeFlags : pImplTypeFlags...Int32* => IMPLTYPEFLAGS*
Windows.Win32.System.Ole.OLEUIBUSYA.dwFlags...System.UInt32 => Windows.Win32.System.Ole.BUSY_DIALOG_FLAGS
Windows.Win32.System.Ole.OLEUIBUSYW.dwFlags...System.UInt32 => Windows.Win32.System.Ole.BUSY_DIALOG_FLAGS
Windows.Win32.System.Ole.ICreateTypeInfo.SetImplTypeFlags : implTypeFlags...Int32 => IMPLTYPEFLAGS
```

### CODE REVIEW

**Review by mikebattista — CHANGES_REQUESTED** [review]
Thanks. This changes the metadata, though, so you'll need to update the baseline.

**Review by mikebattista — CHANGES_REQUESTED** [review]
I'd expect 5 diffs but only see 3. Are there bugs in the missing 2?

**Comment by elachlan** [comment]
> I'd expect 5 diffs but only see 3. Are there bugs in the missing 2?

Thanks, I'll check over it and get back to you here.

**Comment by elachlan** [comment]
I am unsure why those changes are not showing up.

**Review by mikebattista — APPROVED** [review]

**Pull request merged**
