### PR TITLE
Rearrange Direct3D namespaces:

### PR DESCRIPTION
**Pull request by damyanp**
d3dcommon.h -> Windows.Win32.Graphics.Direct3D.
dxcompiler.h -> Windows.Win32.Graphics.Direct3D.Fxc
dxcapi.h is -> Windows.Win32.Graphics.Direct3D.Dxc
d3d11on12.h -> Windows.Win32.Graphics.Direct3D11on12
dxcore*.h -> Windows.Win32.Graphics.DXCore

### CODE REVIEW

**Comment by sotteson1** [comment]
Looks good so far. It will need to update the .winmd too.

**Comment by mikebattista** [comment]
@damyanp this PR is marked as a Draft so we haven't looked too closely or integrated it yet. Are you planning to make more changes?

**Comment by damyanp** [comment]
Thanks for the prod - I don't have any more changes planned.  I'll try and make some time to resolve the conflicts so we can take it out of draft.

**Comment by mikebattista** [comment]
Thanks. A few other headers we needed recommendations for were d3dcaps.h, d3dnthal.h, d3dtypes.h, and ddrawgdi.h.

**Comment by damyanp** [comment]
@mikebattista - I'll try and resolve the merge conflicts again soon, but this PR is ready for review.  I want to use another PR to take in our proposed changes for the other headers you mentioned in https://github.com/microsoft/win32metadata/pull/579#issuecomment-929502524.

**Comment by mikebattista** [comment]
Thanks. Don't worry about merge conflicts. We'll address that as part of the merge.

**Comment by mikebattista** [comment]
While merging the ExcludeFromCrossArch changes, I found yours differed by:

Ado
Audio
Automation
Cryptography
Direct3D
Direct3D11on12
Direct3DDxc
Direct3DDxgi
Direct3DFxc
DShow
DXCore

Are these all intentional changes?

@sotteson1 as well for review. Hard to tell what's expected with the two long lists that both changed.

**Comment by damyanp** [comment]
The various DX ones are.  The others I'm not sure about - when I did the merge a couple of weeks ago those ones I think were in main, but maybe that's changed again.

**Comment by mikebattista** [comment]
Thanks. Steve did a big refactor recently so not sure if the unexpected ones in your list were removed with his changes.

@sotteson1 can you take a look? Can we safely just add the D* items in the list to what's in the master branch and ignore the others?

**Comment by sotteson1** [comment]
The build will tell you at the end which partitions can be added to the list. If it lists any, you can add them to the property. If it doesn't list any, you're good. To get the current list, I commented out the property and let the build tell me what it should be (takes a lot longer because every partition has to get scanned 3 times).

**Pull request merged**
