### PR TITLE
Add short const support, make constant scraping impl. testable

### PR DESCRIPTION
**Pull request by riverar**
Fixes: #1029

Added support for `short` `PSTR`/`PWSTR` constant values in special cases (e.g. `MAKEINTRESOURCE`). Did some light refactoring to the constant parsing code to get some unit testing going. More refactor work is needed; over time we'll eliminate our need for the abstractions dependency.

New ConstantsScraper dependencies:
* System.IO.Abstractions

New test dependencies:
* System.IO.Abstractions
* System.IO.Abstractions.TestingHelpers
* Moq
* MSTest.TestFramework

---

@mikebattista Can you help with the winmd changes comparison script? It doesn't seem to be picking up on the subtle differences here.

### CODE REVIEW

**Comment by mikebattista** [comment]
I thought everyone agreed that we shouldn't be changing the types of these to `short`. See https://github.com/microsoft/win32metadata/issues/1029#issuecomment-1235763743.

**Comment by riverar** [comment]
Here's what the output previously looked like:

```
.field public static literal valuetype Windows.Win32.Foundation.PWSTR TD_WARNING_ICON = int32(-1)
```

And how it looks like afterwards:

```
.field public static literal valuetype Windows.Win32.Foundation.PWSTR TD_WARNING_ICON = int16(-1)
```

**Comment by mikebattista** [comment]
Ok. Can you update the baseline?

**Comment by riverar** [comment]
@mikebattista That's what I was asking you for help with (bottom of PR) 🙃. Doesn't look like it's detecting the changes. If you don't get to it, no worries, I can take a look off work hours.

**Comment by riverar** [comment]
Tweaked the PR text as I realized it was causing some confusion (short constants vs short pwstr constant values). Sorry about that.

**Comment by riverar** [comment]
New diff:
```
Windows.Win32.Media.KernelStreaming.Apis.RT_RCDATA value init changed Int32->Int16
Windows.Win32.Media.KernelStreaming.Apis.RT_STRING value init changed Int32->Int16
Windows.Win32.UI.Controls.Apis.TD_ERROR_ICON value init changed Int32->Int16
Windows.Win32.UI.Controls.Apis.TD_INFORMATION_ICON value init changed Int32->Int16
Windows.Win32.UI.Controls.Apis.TD_SHIELD_ICON value init changed Int32->Int16
Windows.Win32.UI.Controls.Apis.TD_WARNING_ICON value init changed Int32->Int16
Windows.Win32.UI.WindowsAndMessaging.Apis.IDC_APPSTARTING value init changed Int32->Int16
Windows.Win32.UI.WindowsAndMessaging.Apis.IDC_ARROW value init changed Int32->Int16
Windows.Win32.UI.WindowsAndMessaging.Apis.IDC_CROSS value init changed Int32->Int16
Windows.Win32.UI.WindowsAndMessaging.Apis.IDC_HAND value init changed Int32->Int16
Windows.Win32.UI.WindowsAndMessaging.Apis.IDC_HELP value init changed Int32->Int16
Windows.Win32.UI.WindowsAndMessaging.Apis.IDC_IBEAM value init changed Int32->Int16
Windows.Win32.UI.WindowsAndMessaging.Apis.IDC_ICON value init changed Int32->Int16
Windows.Win32.UI.WindowsAndMessaging.Apis.IDC_NO value init changed Int32->Int16
Windows.Win32.UI.WindowsAndMessaging.Apis.IDC_PERSON value init changed Int32->Int16
Windows.Win32.UI.WindowsAndMessaging.Apis.IDC_PIN value init changed Int32->Int16
Windows.Win32.UI.WindowsAndMessaging.Apis.IDC_SIZE value init changed Int32->Int16
Windows.Win32.UI.WindowsAndMessaging.Apis.IDC_SIZEALL value init changed Int32->Int16
Windows.Win32.UI.WindowsAndMessaging.Apis.IDC_SIZENESW value init changed Int32->Int16
Windows.Win32.UI.WindowsAndMessaging.Apis.IDC_SIZENS value init changed Int32->Int16
Windows.Win32.UI.WindowsAndMessaging.Apis.IDC_SIZENWSE value init changed Int32->Int16
Windows.Win32.UI.WindowsAndMessaging.Apis.IDC_SIZEWE value init changed Int32->Int16
Windows.Win32.UI.WindowsAndMessaging.Apis.IDC_UPARROW value init changed Int32->Int16
Windows.Win32.UI.WindowsAndMessaging.Apis.IDC_WAIT value init changed Int32->Int16
Windows.Win32.UI.WindowsAndMessaging.Apis.RT_ACCELERATOR value init changed Int32->Int16
Windows.Win32.UI.WindowsAndMessaging.Apis.RT_ANICURSOR value init changed Int32->Int16
Windows.Win32.UI.WindowsAndMessaging.Apis.RT_ANIICON value init changed Int32->Int16
Windows.Win32.UI.WindowsAndMessaging.Apis.RT_BITMAP value init changed Int32->Int16
Windows.Win32.UI.WindowsAndMessaging.Apis.RT_CURSOR value init changed Int32->Int16
Windows.Win32.UI.WindowsAndMessaging.Apis.RT_DIALOG value init changed Int32->Int16
Windows.Win32.UI.WindowsAndMessaging.Apis.RT_DLGINCLUDE value init changed Int32->Int16
Windows.Win32.UI.WindowsAndMessaging.Apis.RT_FONT value init changed Int32->Int16
Windows.Win32.UI.WindowsAndMessaging.Apis.RT_FONTDIR value init changed Int32->Int16
Windows.Win32.UI.WindowsAndMessaging.Apis.RT_HTML value init changed Int32->Int16
Windows.Win32.UI.WindowsAndMessaging.Apis.RT_ICON value init changed Int32->Int16
Windows.Win32.UI.WindowsAndMessaging.Apis.RT_MENU value init changed Int32->Int16
Windows.Win32.UI.WindowsAndMessaging.Apis.RT_MESSAGETABLE value init changed Int32->Int16
Windows.Win32.UI.WindowsAndMessaging.Apis.RT_PLUGPLAY value init changed Int32->Int16
Windows.Win32.UI.WindowsAndMessaging.Apis.RT_VERSION value init changed Int32->Int16
Windows.Win32.UI.WindowsAndMessaging.Apis.RT_VXD value init changed Int32->Int16
```

**Review by mikebattista — DISMISSED** [review]

**Comment by mikebattista** [comment]
Awesome. Thanks!

**Pull request merged**
