### PR TITLE
Initial support for GDI+

### PR DESCRIPTION
**Pull request by riverar**
Fixes: #1287

### CODE REVIEW

**Comment by riverar** [comment]
@mikebattista Can you share the pipeline errors when you get a chance? Thanks!

**Comment by elachlan** [comment]
@JeremyKuhne You would be interested in this PR.

**Comment by mikebattista** [comment]
```
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:16.41]     Windows.Win32.Tests.IntegrityTests.NoInvalidEmptyDelegates [FAIL]
  Failed Windows.Win32.Tests.IntegrityTests.NoInvalidEmptyDelegates [12 s]
  Error Message:
   Assert.Equal() Failure
Expected: 0
Actual:   -1
  Stack Trace:
     at Windows.Win32.Tests.IntegrityTests.ExecWinmdUtils(String args) in D:\a\1\s\tests\Windows.Win32.Tests\IntegrityTests.cs:line 85
   at Windows.Win32.Tests.IntegrityTests.NoInvalidEmptyDelegates() in D:\a\1\s\tests\Windows.Win32.Tests\IntegrityTests.cs:line 45
  Standard Output Messages:
 Calling: dotnet "D:\a\1\s\bin\Release\net6.0\winmdutils.dll" showEmptyDelegates --winmd "D:\a\1\s\bin\windows.win32.winmd" "@D:\a\1\s\bin\Release\net6.0\assets\emptyDelegatesAllowList.rsp"
 Empty delegates detected:
 DrawImageAbort
 GetThumbnailImageAbort
```

**Comment by riverar** [comment]
Thanks, weird. Will fix this in a few minutes.

**Review by mikebattista — APPROVED** [review]

**Comment by elachlan** [comment]
Thank you @riverar and @mikebattista for your hard work and perseverance with this!

**Pull request merged**
