### PR TITLE
Only load netstandard.dll from the hardcoded path if it wasn't provided by the user

### PR DESCRIPTION
**Pull request by dpaoliello**
## Issue Details:
`ClangSharpSourceToWinmd` currently uses a hard-coded path to find the `netstandard.dll` reference assembly, which is problematic if the user has a project-local version (e.g., using the [`NETStandard.Library.Ref` NuGet package](https://www.nuget.org/packages/NETStandard.Library.Ref)) or otherwise has it in a non-standard location.

## Fix Details:
Only use the hard-coded path if the compilation doesn't already have netstandard 2.1 already in the compilation: this allows users to specify a path using the normal `--ref` command line argument but falls back to the legacy behavior for customers who depend on that.

### CODE REVIEW

**Comment by riverar** [comment]
Hm, would be great to avoid adding some random variable that folks will depend on and we'll have to support forever. Maybe we can come up with a better scheme to find this library in the first place?

**Comment by dpaoliello** [comment]
@riverar I've changed my approach for this: instead of using an env var, what if we only inject netstandard.dll if the user didn't already add it via `--ref`?

**Comment by riverar** [comment]
@dpaoliello Sounds promising; think your last commit got mangled there and can no longer see a diff.

**Comment by dpaoliello** [comment]
> Sounds promising; think your last commit got mangled there and can no longer see a diff.

Yeah, sorry, something messed up the line endings - should be good now.

**Review by riverar — APPROVED** [review]
Nice!

**Review by mikebattista — APPROVED** [review]

**Pull request merged**
