### PR TITLE
Revert "Initial support for GDI+ (#1679)"

### PR DESCRIPTION
**Pull request by riverar**
Reverting 0c63f94aea98688b200a3964365aae60095c83e0 to restore branch status. We'll take another whack at GDI+ shortly.

### CODE REVIEW

**Review by mikebattista — APPROVED** [review]

**Comment by elachlan** [comment]
Should we re-open #1287?

**Comment by riverar** [comment]
@elachlan Oops, thanks for the heads up. Done. Will get that fixed up in the next few days, tricker than normal due to the flat API not being cleanly separate from the C++ goop.

**Comment by elachlan** [comment]
Thanks for looking at it. It does seem a bit of a hassle trying to wrangle object oriented code to functional. Even if it's just the method calls.

**Comment by mikebattista** [comment]
Yes thanks for looking at it. I got stuck trying to add them so was happy to see you got farther than I did.

**Pull request merged**
