### PR TITLE
Add FreeWith(CoTaskMemFree) attribute to BITS API params

### PR DESCRIPTION
**Pull request by riverar**
Adds `FreeWith(CoTaskMemFree)` attribute to a handful of Background Intelligent Transfer Service (BITS) API parameters.

Unblocks: microsoft/windows-rs#1559

Metadata diff:
```
Windows.Win32.Networking.BackgroundIntelligentTransferService.IBackgroundCopyJob.GetOwner : pVal : [Out] => [Out,FreeWith(CoTaskMemFree)]
Windows.Win32.Networking.BackgroundIntelligentTransferService.IBackgroundCopyJob.GetDisplayName : pVal : [Out] => [Out,FreeWith(CoTaskMemFree)]
Windows.Win32.Networking.BackgroundIntelligentTransferService.IBackgroundCopyJob.GetDescription : pVal : [Out] => [Out,FreeWith(CoTaskMemFree)]
Windows.Win32.Networking.BackgroundIntelligentTransferService.IBackgroundCopyJob.GetProxySettings : pProxyList : [Out] => [Out,FreeWith(CoTaskMemFree)]
Windows.Win32.Networking.BackgroundIntelligentTransferService.IBackgroundCopyJob.GetProxySettings : pProxyBypassList : [Out] => [Out,FreeWith(CoTaskMemFree)]
Windows.Win32.Networking.BackgroundIntelligentTransferService.IBackgroundCopyManager.GetErrorDescription : pErrorDescription : [Out] => [Out,FreeWith(CoTaskMemFree)]
Windows.Win32.Networking.BackgroundIntelligentTransferService.IBackgroundCopyFile2.GetFileRanges : Ranges : [Out,NativeArrayInfo(CountParamIndex=0)] => [Out,NativeArrayInfo(CountParamIndex=0),FreeWith(CoTaskMemFree)]
Windows.Win32.Networking.BackgroundIntelligentTransferService.IBackgroundCopyJobHttpOptions.GetClientCertificate : ppCertHashBlob : [Optional,Out,NativeArrayInfo(CountConst=20)] => [Optional,Out,NativeArrayInfo(CountConst=20),FreeWith(CoTaskMemFree)]
Windows.Win32.Networking.BackgroundIntelligentTransferService.IBackgroundCopyJobHttpOptions.GetClientCertificate : pSubjectName : [Optional,Out] => [Optional,Out,FreeWith(CoTaskMemFree)]
Windows.Win32.Networking.BackgroundIntelligentTransferService.IBackgroundCopyJobHttpOptions.GetCustomHeaders : pRequestHeaders : [Optional,Out] => [Optional,Out,FreeWith(CoTaskMemFree)]
Windows.Win32.Networking.BackgroundIntelligentTransferService.IBackgroundCopyFile3.GetTemporaryName : pFilename : [Out] => [Out,FreeWith(CoTaskMemFree)]
Windows.Win32.Networking.BackgroundIntelligentTransferService.IBackgroundCopyJobHttpOptions2.GetHttpMethod : method : [Out] => [Out,FreeWith(CoTaskMemFree)]
```

### CODE REVIEW

**Comment by riverar** [comment]
I don't have access to ADO logs. Can someone share why the build is failing?

**Comment by kennykerr** [comment]
Comparing D:\a\1\s\bin\Windows.Win32.winmd against baseline D:\a\1\s\scripts\BaselineWinmd\Windows.Win32.winmd...
Calling: dotnet D:\a\1\s\bin\release\net5.0\WinmdUtils.dll compare --first D:\a\1\s\scripts\BaselineWinmd\Windows.Win32.winmd --second D:\a\1\s\bin\Windows.Win32.winmd
Windows.Win32.Networking.BackgroundIntelligentTransferService.IBackgroundCopyJob.GetOwner : pVal : [Out] => [Out,FreeWith(CoTaskMemFree)]
Windows.Win32.Networking.BackgroundIntelligentTransferService.IBackgroundCopyJob.GetDisplayName : pVal : [Out] => [Out,FreeWith(CoTaskMemFree)]
Windows.Win32.Networking.BackgroundIntelligentTransferService.IBackgroundCopyJob.GetDescription : pVal : [Out] => [Out,FreeWith(CoTaskMemFree)]
Windows.Win32.Networking.BackgroundIntelligentTransferService.IBackgroundCopyJob.GetProxySettings : pProxyList : [Out] => [Out,FreeWith(CoTaskMemFree)]
Windows.Win32.Networking.BackgroundIntelligentTransferService.IBackgroundCopyJob.GetProxySettings : pProxyBypassList : [Out] => [Out,FreeWith(CoTaskMemFree)]
Windows.Win32.Networking.BackgroundIntelligentTransferService.IBackgroundCopyManager.GetErrorDescription : pErrorDescription : [Out] => [Out,FreeWith(CoTaskMemFree)]
Windows.Win32.Networking.BackgroundIntelligentTransferService.IBackgroundCopyFile2.GetFileRanges : Ranges : [Out,NativeArrayInfo(CountParamIndex=0)] => [Out,NativeArrayInfo(CountParamIndex=0),FreeWith(CoTaskMemFree)]
Windows.Win32.Networking.BackgroundIntelligentTransferService.IBackgroundCopyJobHttpOptions.GetClientCertificate : ppCertHashBlob : [Optional,Out,NativeArrayInfo(CountConst=20)] => [Optional,Out,NativeArrayInfo(CountConst=20),FreeWith(CoTaskMemFree)]
Windows.Win32.Networking.BackgroundIntelligentTransferService.IBackgroundCopyJobHttpOptions.GetClientCertificate : pSubjectName : [Optional,Out] => [Optional,Out,FreeWith(CoTaskMemFree)]
Windows.Win32.Networking.BackgroundIntelligentTransferService.IBackgroundCopyJobHttpOptions.GetCustomHeaders : pRequestHeaders : [Optional,Out] => [Optional,Out,FreeWith(CoTaskMemFree)]
Windows.Win32.Networking.BackgroundIntelligentTransferService.IBackgroundCopyFile3.GetTemporaryName : pFilename : [Out] => [Out,FreeWith(CoTaskMemFree)]
Windows.Win32.Networking.BackgroundIntelligentTransferService.IBackgroundCopyJobHttpOptions2.GetHttpMethod : method : [Out] => [Out,FreeWith(CoTaskMemFree)]
If all the differences are expected, please update the baseline by doing this:
copy D:\a\1\s\bin\Windows.Win32.winmd D:\a\1\s\scripts\BaselineWinmd\Windows.Win32.winmd
##[error]PowerShell exited with code '1'.
Finishing: Do tests

**Comment by kennykerr** [comment]
Now its failing here:

```
Time Elapsed 00:01:54.77
Could not start Developer PowerShell using the script path.
Attempting to launch from the latest Visual Studio installation.
Could not start Developer PowerShell from the latest Visual Studio installation.

ForEach-Object : The variable '$i' cannot be retrieved because it has not been set.
At C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\Launch-VsDevShell.ps1:223 char:9
+         ForEach-Object {} { $i++; $_ | Add-Member -NotePropertyName " …
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (i:String) [ForEach-Object], RuntimeException
+ FullyQualifiedErrorId : VariableIsUndefined,Microsoft.PowerShell.Commands.ForEachObjectCommand
##[error]PowerShell exited with code '1'.
Finishing: GenerateMetadataSource.ps1 - x64
```

**Comment by mikebattista** [comment]
Is this safe to merge now with your workaround for the VS issue?

**Comment by riverar** [comment]
@mikebattista Can we kick off a new build for validation?

**Review by mikebattista — APPROVED** [review]

**Comment by riverar** [comment]
@mikebattista Looks good, thanks!

**Pull request merged**
