### PR TITLE
Add .dll suffix to remaining library mappings

### PR DESCRIPTION
**Pull request by riverar**
Repeat PR #1022 with new metadata per request. (cc: @mikebattista)

Fixes: #1021

### CODE REVIEW

**Comment by mikebattista** [comment]
Same issue. I can't accept this request until I guess the winmd is excluded. This is breaking checkouts as well as signing in the build pipelines. Something about this particular change is triggering the issue since I've made several other changes to the winmd without any issues.

**Comment by riverar** [comment]
@mikebattista OK standby. Let me submit the winmd to Defender now.

**Comment by mikebattista** [comment]
Also to be clear, Windows Defender is reporting a Git LFS path, in case that affects how we handle things. The winmd is stored in Git LFS.

image

**Comment by riverar** [comment]
Yep, submitted to WDSI.

Submission ID: 73c3295e-ec5e-4969-ba25-b1fa72fb9b45
Status: In progress
Submitted: Aug 2, 2022 9:22:05 AM
https://www.microsoft.com/en-us/wdsi/submission/73c3295e-ec5e-4969-ba25-b1fa72fb9b45

May or may not be visible to FTEs. The analysts are usually very quick so could see the exclusion added to antimalware signatures as soon as today.

**Comment by riverar** [comment]
From Microsoft:

```
At this time, the submitted files do not meet our criteria for malware or potentially unwanted applications. The detection has been removed. Please follow the steps below to clear cached detections and obtain the latest malware definitions.

1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
3. Run "MpCmdRun.exe -SignatureUpdate"
```

@mikebattista Looks like we're good to go. I'll rebase and you can give it another spin.

**Review by mikebattista — APPROVED** [review]

**Comment by mikebattista** [comment]
Reset the malware definitions but still getting defender alerts when I check out your PR.

image

**Review by mikebattista — DISMISSED** [review]
Need to address Windows Defender errors.

**Comment by riverar** [comment]
I can't reproduce this, can you share your definitions version number?

image

**Comment by mikebattista** [comment]
image

**Comment by riverar** [comment]
I can reproduce this now, looks like the Defender folks lazily added a winmd-only exclusion. Submitting another ticket now.

**Comment by mikebattista** [comment]
VSCode reports the below error when I checkout your PR:

Error downloading object: scripts/BaselineWinmd/Windows.Win32.winmd (3d9c927): Smudge error: error opening media file: open C:\win32metadata\.git\lfs\objects\3d\9c\3d9c927862a1ae959d42969c214051286e6c2ece8bb627e307e984e807c83a02: Operation did not complete successfully because the file contains a virus or potentially unwanted software. Errors logged to C:\win32metadata\.git\lfs\logs\20220803T183358.2480326.log Use `git lfs logs last` to view the log. error: external filter 'git-lfs filter-process' failed fatal: scripts/BaselineWinmd/Windows.Win32.winmd: smudge filter lfs failed . Please check git output for more details

**Comment by riverar** [comment]
Submission ID: edc6c9a0-0692-42e7-9625-5d45b579db17
Status: Submitted
Submitted: Aug 3, 2022 6:43:50 PM
https://www.microsoft.com/en-us/wdsi/submission/edc6c9a0-0692-42e7-9625-5d45b579db17

And now we wait again!

**Comment by riverar** [comment]
They reportedly removed the lfs detection (update your definitions) but now I'm triggering on the `winmd` again sigh.

Maybe this is a good time to rip off the Band-Aid and stop checking in binaries. It would also improve multiple PR workflow too.

**Comment by mikebattista** [comment]
Unfortunate. @AArnott had some ideas for being able to support diff workflows in local changes and in PRs without a checked in binary.

**Comment by riverar** [comment]
Is there anything we can do in the interm to get this change in? Without this change, downstream projections can't 100% know when to apply a file extension and which one to apply.

**Comment by mikebattista** [comment]
> Is there anything we can do in the interm to get this change in? Without this change, downstream projections can't 100% know when to apply a file extension and which one to apply.

I'm not sure. I need to be able to fix other issues and sign and ship updated metadata packages, and the Defender issues are blocking that.

**Review by sotteson1 — COMMENTED** [review]
The new system gets rid of the baseline .winmd, and instead updates a text file that will include the diff of your changes. (The output of the build is meant to help you automate your additions to this file.) Sorry to randomize your PR but I think this system will be a lot nicer for merges in the future.

**Comment by riverar** [comment]
I'll have to take a look but sounds like we'll run into the same problems with PR concurrency.

**Comment by AArnott** [comment]
> we'll run into the same problems with PR concurrency.

Yes, although it will be easier to merge, and won't require re-running the full build.

To avoid merge conflicts entirely, this would require eliminating the checked in file. The file could be produced by the build, by teaching the build to download the equivalent file from a prior Azure Pipelines CI build.

**Comment by riverar** [comment]
@mikebattista Can clear your flag now 🥳

**Comment by sotteson1** [comment]
Delete the baseline .winmd as we don't use that anymore.

**Comment by sotteson1** [comment]
Hmm. I wonder if an easier way to fix this would be for the emitter to append the .dll if there's no extension. What do you think @riverar?

**Comment by riverar** [comment]
@sotteson1 Your call, but I think I prefer to just make everything explicit and call it a day. If we do this in the emitter, we may have to then add a bunch of special code to handle assemblies like Windows.Data.Pdf.

**Comment by kennykerr** [comment]
I don't have an opinion on the approach, but I am waiting on this fix before the next Rust ingestion.

**Review by sotteson1 — APPROVED** [review]

**Pull request merged**
