### PR TITLE
Add AlternateSuccessCodes to IShellFolder::EnumObjects

### PR DESCRIPTION
**Pull request by ArturKovacs**
According to https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-ishellfolder-enumobjects

> Returns `S_OK` if successful, or an error value otherwise. Some implementations may also return `S_FALSE`, indicating that there are no children matching the grfFlags that were passed in.

### CODE REVIEW

**Comment by sotteson1** [comment]
Thanks for this. Please build it using ````.\DoAll.ps1```` -Clean to make sure your change has the right effect. At the end of the build, it will also tell you how to update the baseline .winmd from your changes.

**Comment by ArturKovacs** [comment]
All done, the diff output was
```
Calling: dotnet C:\Users\kovac\personal\source\win32metadata\bin\release\netcoreapp3.1\WinmdUtils.dll compare --first C:\Users\kovac\personal\source\win32metadata\scripts\BaselineWinmd\Windows.Win32.winmd --second C:\Users\kovac\personal\source\win32metadata\bin\Windows.Win32.winmd
Windows.Win32.UI.Shell.IShellFolder.EnumObjects : return :  => [AlternateSuccessCodes]
If all the differences are expected, please update the baseline by doing this:
```

**Comment by mikebattista** [comment]
Thanks for filing. I will resolve the conflicts and merge.

**Comment by ArturKovacs** [comment]
Thank you! Feel free to push to this branch if needed.

**Comment by mikebattista** [comment]
Merged with https://github.com/microsoft/win32metadata/commit/ec269e28b5b1623dc1565acf2635c91936bc4169.

**Pull request closed without merging**
