### PR TITLE
Transform multicharacter literals to integers when scraping guids

### PR DESCRIPTION
**Pull request by riverar**
GUID constants defined with multicharacter literals (C++) were causing the creation/emission of invalid GUID attributes in output metadata. This change introduces a new helper to transform these literals into their equivalent integer constants (in hexadecimal) compatible with GuidAttribute constructors.

Fixes: #1116

### CODE REVIEW

**Comment by sotteson1** [comment]
Thanks for the great tests too!

**Review by sotteson1 — APPROVED** [review]

**Comment by riverar** [comment]
@sotteson1 Looks like the build failed in master, can you fish out the error? I can't see those builds.

**Comment by sotteson1** [comment]
No worries, I'll fix it up. The merge added an empty line in the changes txt file. I'll make the code resilient for that kind of thing.

**Pull request merged**
