### PR TITLE
Namespace refactoring

### PR DESCRIPTION
**Pull request by mikebattista**
More namespace refactoring.

Need help resolving the below duplicate constants errors before merging.

Duplicate constants/enum names detected:
GUID_DEVINTERFACE_USBPRINT
  Windows.Win32.Graphics.Printing.Apis
  Windows.Win32.Graphics.Printing.Apis
GUID_DEVINTERFACE_IPPUSB_PRINT
  Windows.Win32.Graphics.Printing.Apis
  Windows.Win32.Graphics.Printing.Apis
NOTIFICATION_RELEASE
  Windows.Win32.Graphics.Printing.Apis
  Windows.Win32.Graphics.Printing.Apis
PRINT_APP_BIDI_NOTIFY_CHANNEL
  Windows.Win32.Graphics.Printing.Apis
  Windows.Win32.Graphics.Printing.Apis
PRINT_PORT_MONITOR_NOTIFY_CHANNEL
  Windows.Win32.Graphics.Printing.Apis
  Windows.Win32.Graphics.Printing.Apis

### CODE REVIEW

**Comment by mikebattista** [comment]
@sotteson1 the CI build is failing saying the below were removed from the baseline, but I can't reproduce with a clean build locally. Local builds work fine with no differences. The baseline winmds on my machine from master and my branch don't have these APIs, and I can't find them defined anywhere in the SDK. In fact, we have another [PR](https://github.com/microsoft/win32metadata/pull/474) to add most of these manually, so it's not clear why the baseline used in the CI build has them.

```
Comparing E:\BA\31\s\bin\Windows.Win32.winmd against baseline E:\BA\31\s\scripts\BaselineWinmd\Windows.Win32.winmd...
Calling: dotnet E:\BA\31\s\bin\release\netcoreapp3.1\WinmdUtils.dll compare --first E:\BA\31\s\scripts\BaselineWinmd\Windows.Win32.winmd --second E:\BA\31\s\bin\Windows.Win32.winmd
Windows.Win32.Graphics.Hlsl.Apis.DXC_CP_UTF8 not found in 2nd winmd
Windows.Win32.Graphics.Hlsl.Apis.DXC_CP_UTF16 not found in 2nd winmd
Windows.Win32.Graphics.Hlsl.Apis.DXC_CP_ACP not found in 2nd winmd
Windows.Win32.Graphics.Hlsl.Apis.DXC_HASHFLAG_INCLUDES_SOURCE not found in 2nd winmd
```

**Comment by MarijnS95** [comment]
@mikebattista the same came up in https://github.com/microsoft/win32metadata/pull/450#issuecomment-831472938, those constants/preprocessor-defines do not exist in the current SDK.

Note that the last master commit failed. I cannot see the logs, but possibly @sotteson1 regenerated with a newer SDK making those constants reappear again, clarifying the failure and the reason you see these errors in this PR too.

**Comment by mikebattista** [comment]
Thanks. I just noticed master was failing as well as of https://github.com/microsoft/win32metadata/commit/24056ce063db2b9b3fb000b1a341318663bf305f which I just merged into this branch.

The `launchsettings.json` changes look suspicious. There might be a bug there.

**Comment by sotteson1** [comment]
> Thanks. I just noticed master was failing as well as of [24056ce](https://github.com/microsoft/win32metadata/commit/24056ce063db2b9b3fb000b1a341318663bf305f) which I just merged into this branch.
> 
> The `launchsettings.json` changes look suspicious. There might be a bug there.

That file is only used when debugging in VS.

**Comment by mikebattista** [comment]
> @mikebattista the same came up in [#450 (comment)](https://github.com/microsoft/win32metadata/pull/450#issuecomment-831472938), those constants/preprocessor-defines do not exist in the current SDK.
> 
> Note that the last master commit failed. I cannot see the logs, but possibly @sotteson1 regenerated with a newer SDK in [24056ce](https://github.com/microsoft/win32metadata/commit/24056ce063db2b9b3fb000b1a341318663bf305f) (showing a similar size decrease as the comment linked above) making those constants reappear, clarifying the failure and the reason you see these errors in this PR too.

@MarijnS95 you might be right here but it might be a bug that the constant scraper is pulling things in from newer SDKs installed on the local machine, rather than the SDK that is expected to be used from the repo. Steve is looking into it.

**Pull request merged**
