### PR TITLE
Fix build error

### PR DESCRIPTION
**Pull request by elachlan**
Fix the build error and have a nice output.

### CODE REVIEW

**Comment by elachlan** [comment]
@sotteson1 this feels a bit nicer than `write-error`.

**Comment by sotteson1** [comment]
I purposely changed this to an error, because I want to be clear the build is failing until the script is run to update the known exceptions.

**Comment by elachlan** [comment]
Maybe we can highlight it red then instead? This error makes it seem like the script is broken.

**Comment by riverar** [comment]
`Write-Error` writes to the error stream amongst other things. Feel free to propose an alternative that preserves this behavior or lets close the PR and move on.

**Pull request closed without merging**
